#include "basis_params.hpp"
#include "hamiltonian.hpp"
#include "derivatives.hpp"
#include "hamiltonian_gradient.hpp"
#include "tdvp_solver.hpp"
#include "svm.hpp"
#include <iostream>
#include <iomanip>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <chrono>

using namespace ecg1d;

// Read basis function parameters from a CSV file generated by the Python script.
// Format: one line per complex number, "real,imag"
// File structure: for each basis function: u(1), A(N*N), B(N*N), R(N), name(1)
static std::vector<BasisParams> load_basis_from_csv(const std::string& filename, int N, int basis_n) {
    std::ifstream fin(filename);
    if (!fin.is_open()) {
        std::cerr << "Cannot open " << filename << std::endl;
        return {};
    }

    auto read_complex = [&]() -> Cd {
        std::string line;
        std::getline(fin, line);
        std::stringstream ss(line);
        double re, im;
        char comma;
        ss >> re >> comma >> im;
        return Cd(re, im);
    };

    auto read_int = [&]() -> int {
        std::string line;
        std::getline(fin, line);
        return std::stoi(line);
    };

    std::vector<BasisParams> basis(basis_n);
    for (int k = 0; k < basis_n; k++) {
        basis[k].u = read_complex();
        basis[k].A = MatrixXcd(N, N);
        for (int i = 0; i < N; i++)
            for (int j = 0; j < N; j++)
                basis[k].A(i, j) = read_complex();
        basis[k].B = MatrixXcd(N, N);
        for (int i = 0; i < N; i++)
            for (int j = 0; j < N; j++)
                basis[k].B(i, j) = read_complex();
        basis[k].R = VectorXcd(N);
        for (int i = 0; i < N; i++)
            basis[k].R(i) = read_complex();
        basis[k].name = read_int();
    }
    return basis;
}

static void print_complex(const std::string& label, Cd v) {
    std::cout << label << ": " << v.real() << " + " << v.imag() << "i" << std::endl;
}

static void run_phase1(const std::vector<BasisParams>& basis, int N) {
    std::cout << "=== Phase 1: Functionals ===" << std::endl;

    Cd S = overlap(basis);
    print_complex("Overlap", S);

    Cd T = kinetic_energy_functional(basis);
    print_complex("Kinetic", T);

    Cd V = Harmonic_functional(basis);
    print_complex("Harmonic", V);

    if (N >= 2) {
        Cd D = Delta_contact_functional(basis);
        print_complex("Delta", D);

        Cd G = Gaussian_interaction_functional(basis);
        print_complex("Gaussian", G);
    }

    Cd K_val = kicking_term_functional(basis);
    print_complex("Kicking", K_val);

    Cd E = (T + V) / S;
    print_complex("E(T+V)/S", E);
}

static void run_phase2(const std::vector<BasisParams>& basis, int N) {
    std::cout << "\n=== Phase 2: Derivatives ===" << std::endl;

    int name0 = basis[0].name;
    int name1 = basis[1].name;

    // partial_z_first tests
    Cd v;

    v = partial_z_first(1, true, basis, name0, 0, 0);
    print_complex("pz_first(1,T," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_first(1, false, basis, name0, 0, 0);
    print_complex("pz_first(1,F," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_first(2, true, basis, name0, 0, 0);
    print_complex("pz_first(2,T," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_first(2, false, basis, name0, 0, 0);
    print_complex("pz_first(2,F," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_first(3, true, basis, name0, 0, 0);
    print_complex("pz_first(3,T," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_first(3, false, basis, name1, 0, 0);
    print_complex("pz_first(3,F," + std::to_string(name1) + ",0,0)", v);

    v = partial_z_first(4, true, basis, name0, 0, 0);
    print_complex("pz_first(4,T," + std::to_string(name0) + ",0,0)", v);

    if (N >= 2) {
        v = partial_z_first(4, true, basis, name0, 0, 1);
        print_complex("pz_first(4,T," + std::to_string(name0) + ",0,1)", v);
    }

    // partial_z_second tests
    v = partial_z_second(2, 2, basis, name0, 0, 0, name0, 0, 0);
    print_complex("pz_second(2,2," + std::to_string(name0) + ",0,0," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_second(1, 1, basis, name0, 0, 0, name0, 0, 0);
    print_complex("pz_second(1,1," + std::to_string(name0) + ",0,0," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_second(1, 2, basis, name0, 0, 0, name0, 0, 0);
    print_complex("pz_second(1,2," + std::to_string(name0) + ",0,0," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_second(3, 2, basis, name0, 0, 0, name0, 0, 0);
    print_complex("pz_second(3,2," + std::to_string(name0) + ",0,0," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_second(4, 2, basis, name0, 0, 0, name0, 0, 0);
    print_complex("pz_second(4,2," + std::to_string(name0) + ",0,0," + std::to_string(name0) + ",0,0)", v);

    if (N >= 2) {
        v = partial_z_second(4, 2, basis, name0, 0, 1, name0, 0, 0);
        print_complex("pz_second(4,2," + std::to_string(name0) + ",0,1," + std::to_string(name0) + ",0,0)", v);
    }

    // calculate_C tests
    v = calculate_C(1, name0, 0, 0, 1, name0, 0, 0, basis);
    print_complex("C(1," + std::to_string(name0) + ",0,0,1," + std::to_string(name0) + ",0,0)", v);

    v = calculate_C(2, name0, 0, 0, 2, name0, 0, 0, basis);
    print_complex("C(2," + std::to_string(name0) + ",0,0,2," + std::to_string(name0) + ",0,0)", v);

    v = calculate_C(3, name0, 0, 0, 2, name0, 0, 0, basis);
    print_complex("C(3," + std::to_string(name0) + ",0,0,2," + std::to_string(name0) + ",0,0)", v);

    v = calculate_C(4, name0, 0, 0, 2, name0, 0, 0, basis);
    print_complex("C(4," + std::to_string(name0) + ",0,0,2," + std::to_string(name0) + ",0,0)", v);
}

static void run_phase3_gradient(const std::vector<BasisParams>& basis, int N) {
    std::cout << "\n=== Phase 3: Hamiltonian Gradients ===" << std::endl;

    int name0 = basis[0].name;
    int name1 = (basis.size() > 1) ? basis[1].name : name0;
    std::string sn0 = std::to_string(name0);
    std::string sn1 = std::to_string(name1);

    auto rf_str = [](bool r) { return r ? "T" : "F"; };

    // Test all Hamiltonian gradient terms for a1={1,2,3}, Real={T,F}
    for (int a1 : {1, 2, 3}) {
        int a2 = name0;
        for (bool real_flag : {true, false}) {
            std::string tag = "(" + std::to_string(a1) + "," + rf_str(real_flag) + "," + sn0 + ",0,0)";

            Cd gT = calculate_Hamiltonian_kinetic_partial(a1, a2, 0, 0, real_flag, basis);
            print_complex("gKinetic" + tag, gT);

            Cd gW = calculate_Hamiltonian_harmonic_partial(a1, a2, 0, 0, real_flag, basis);
            print_complex("gHarmonic" + tag, gW);

            if (N >= 2) {
                Cd gD = calculate_Hamiltonian_delta_partial(a1, a2, 0, 0, real_flag, basis);
                print_complex("gDelta" + tag, gD);

                Cd gG = calculate_Hamiltonian_gaussian_partial(a1, a2, 0, 0, real_flag, basis);
                print_complex("gGaussian" + tag, gG);
            }

            Cd gK = calculate_Hamiltonian_kicking_partial(a1, a2, 0, 0, real_flag, basis);
            print_complex("gKicking" + tag, gK);
        }
    }

    // Also test with a different basis index (name1) for a1=2,3
    if (basis.size() > 1) {
        for (int a1 : {2, 3}) {
            for (bool real_flag : {true, false}) {
                std::string tag = "(" + std::to_string(a1) + "," + rf_str(real_flag) + "," + sn1 + ",0,0)";

                Cd gT = calculate_Hamiltonian_kinetic_partial(a1, name1, 0, 0, real_flag, basis);
                print_complex("gKinetic" + tag, gT);

                Cd gW = calculate_Hamiltonian_harmonic_partial(a1, name1, 0, 0, real_flag, basis);
                print_complex("gHarmonic" + tag, gW);

                if (N >= 2) {
                    Cd gD = calculate_Hamiltonian_delta_partial(a1, name1, 0, 0, real_flag, basis);
                    print_complex("gDelta" + tag, gD);

                    Cd gG = calculate_Hamiltonian_gaussian_partial(a1, name1, 0, 0, real_flag, basis);
                    print_complex("gGaussian" + tag, gG);
                }

                Cd gK = calculate_Hamiltonian_kicking_partial(a1, name1, 0, 0, real_flag, basis);
                print_complex("gKicking" + tag, gK);
            }
        }
    }

    // Test a1=4 (A matrix derivative) if N >= 2
    if (N >= 2) {
        for (bool real_flag : {true, false}) {
            std::string tag = "(4," + std::string(rf_str(real_flag)) + "," + sn0 + ",0,0)";

            Cd gT = calculate_Hamiltonian_kinetic_partial(4, name0, 0, 0, real_flag, basis);
            print_complex("gKinetic" + tag, gT);

            Cd gW = calculate_Hamiltonian_harmonic_partial(4, name0, 0, 0, real_flag, basis);
            print_complex("gHarmonic" + tag, gW);

            Cd gD = calculate_Hamiltonian_delta_partial(4, name0, 0, 0, real_flag, basis);
            print_complex("gDelta" + tag, gD);

            Cd gG = calculate_Hamiltonian_gaussian_partial(4, name0, 0, 0, real_flag, basis);
            print_complex("gGaussian" + tag, gG);

            Cd gK = calculate_Hamiltonian_kicking_partial(4, name0, 0, 0, real_flag, basis);
            print_complex("gKicking" + tag, gK);

            // Also test (0,1) for off-diagonal
            std::string tag2 = "(4," + std::string(rf_str(real_flag)) + "," + sn0 + ",0,1)";

            gT = calculate_Hamiltonian_kinetic_partial(4, name0, 0, 1, real_flag, basis);
            print_complex("gKinetic" + tag2, gT);

            gW = calculate_Hamiltonian_harmonic_partial(4, name0, 0, 1, real_flag, basis);
            print_complex("gHarmonic" + tag2, gW);

            gD = calculate_Hamiltonian_delta_partial(4, name0, 0, 1, real_flag, basis);
            print_complex("gDelta" + tag2, gD);

            gG = calculate_Hamiltonian_gaussian_partial(4, name0, 0, 1, real_flag, basis);
            print_complex("gGaussian" + tag2, gG);

            gK = calculate_Hamiltonian_kicking_partial(4, name0, 0, 1, real_flag, basis);
            print_complex("gKicking" + tag2, gK);
        }
    }
}

static void run_phase3_tdvp() {
    std::cout << "\n=== Phase 3: TDVP Evolution (1-particle harmonic) ===" << std::endl;

    // Same initial conditions as Python Verification_One_Particle_Harmonic_1.py
    int N = 1;
    std::vector<BasisParams> basis;
    basis.push_back(BasisParams::from_arrays(
        Cd(1.0, 0.0),
        (MatrixXcd(1,1) << Cd(0.1, 0.1)).finished(),
        (MatrixXcd(1,1) << Cd(0.3, 0.1)).finished(),
        (VectorXcd(1) << Cd(0.2, 0.1)).finished(),
        0
    ));

    int basis_n = static_cast<int>(basis.size());

    // Build alpha_z_list matching Python
    std::vector<AlphaIndex> alpha_z_list;
    // u parameters (a1=1)
    for (int i = 0; i < basis_n; i++)
        alpha_z_list.push_back({1, i, 0, 0});
    // B parameters (a1=2)
    for (int i = 0; i < basis_n; i++)
        for (int j = 0; j < N; j++)
            alpha_z_list.push_back({2, i, j, 0});
    // R parameters (a1=3)
    for (int i = 0; i < basis_n; i++)
        for (int j = 0; j < N; j++)
            alpha_z_list.push_back({3, i, j, 0});

    auto terms = HamiltonianTerms::kinetic_harmonic();

    // Compare gradients with Python
    std::cout << "--- Gradient comparison (1-particle, kinetic+harmonic) ---" << std::endl;
    for (int a1 : {2, 3}) {
        for (bool rf : {true, false}) {
            Cd gT = calculate_Hamiltonian_kinetic_partial(a1, 0, 0, 0, rf, basis);
            Cd gW = calculate_Hamiltonian_harmonic_partial(a1, 0, 0, 0, rf, basis);
            std::string rl = rf ? "Real" : "Imag";
            std::cout << "a1=" << a1 << " " << rl
                      << ": gT=" << gT << ", gW=" << gW << ", total=" << (gT+gW) << std::endl;
        }
    }

    Cd E0 = compute_total_energy(basis, terms);
    std::cout << "Initial E = " << E0.real() << std::endl;
    std::cout << "Expected ground state E = 0.5 (hbar*omega/2)" << std::endl;

    evolution(alpha_z_list, basis, 1e-3, 5000, 1e-12, terms);

    Cd E_final = compute_total_energy(basis, terms);
    std::cout << "Final E = " << std::setprecision(10) << E_final.real() << std::endl;
    std::cout << "Error from 0.5 = " << std::scientific << (E_final.real() - 0.5) << std::endl;
}

// Build alpha_z_list for TDVP (including A matrix parameters for N>=2)
static std::vector<AlphaIndex> build_alpha_z_list(int basis_n, int N) {
    std::vector<AlphaIndex> alpha_z_list;
    // u parameters (a1=1)
    for (int i = 0; i < basis_n; i++)
        alpha_z_list.push_back({1, i, 0, 0});
    // B parameters (a1=2)
    for (int i = 0; i < basis_n; i++)
        for (int j = 0; j < N; j++)
            alpha_z_list.push_back({2, i, j, 0});
    // R parameters (a1=3)
    for (int i = 0; i < basis_n; i++)
        for (int j = 0; j < N; j++)
            alpha_z_list.push_back({3, i, j, 0});
    // A parameters (a1=4), upper triangle only
    for (int i = 0; i < basis_n; i++)
        for (int j = 0; j < N; j++)
            for (int k = j; k < N; k++)
                alpha_z_list.push_back({4, i, j, k});

    return alpha_z_list;
}

// Run the full SVM + stochastic refinement + TDVP pipeline
static void run_svm_tdvp(const std::string& label,
                          const HamiltonianTerms& terms,
                          double E_exact,
                          int K_max = 15, int svm_trials = 5000,
                          int refine_trials = 500, int refine_rounds = 30,
                          int tdvp_steps = 300) {
    int N = 2;
    auto t0 = std::chrono::steady_clock::now();

    // Phase 1: SVM basis construction
    std::cout << "\n=== SVM + TDVP: " << label << " ===" << std::endl;
    std::cout << "Target E = " << std::setprecision(10) << E_exact << std::endl;
    std::cout << "\n--- Phase 1: Stochastic Variational Method ---" << std::endl;

    auto svm = svm_build_basis(N, K_max, svm_trials, terms, 42);
    double E_svm = lowest_energy(svm.H, svm.S);
    auto t1 = std::chrono::steady_clock::now();
    double dt1 = std::chrono::duration<double>(t1 - t0).count();
    std::cout << "SVM result: E = " << std::setprecision(10) << E_svm
              << "  (error = " << std::scientific << (E_svm - E_exact)
              << std::defaultfloat << ")" << std::endl;
    std::cout << "Phase 1 time: " << std::fixed << std::setprecision(1) << dt1 << "s" << std::endl;

    // Phase 2: Stochastic refinement (disabled — set refine_rounds=0 to skip)
    PermutationSet perms = PermutationSet::generate(N);
    SvmResult refined = {svm.basis, svm.H, svm.S};
    double E_refine = E_svm;
    auto t2 = t1;

    // Phase 3: TDVP refinement
    std::cout << "\n--- Phase 2: TDVP refinement ---" << std::endl;
    set_u_from_eigenvector(refined.basis, refined.H, refined.S);

    int basis_n = static_cast<int>(refined.basis.size());
    auto alpha_z_list = build_alpha_z_list(basis_n, N);

    evolution(alpha_z_list, refined.basis, 1e-2, tdvp_steps, 1e-10, terms);

    // Final energy from eigenvalue approach
    auto [H_final, S_final] = build_HS(refined.basis, perms, terms);
    double E_final = lowest_energy(H_final, S_final);
    auto t3 = std::chrono::steady_clock::now();
    double dt3 = std::chrono::duration<double>(t3 - t2).count();

    std::cout << "\nPhase 2 time: " << std::fixed << std::setprecision(1) << dt3 << "s" << std::endl;

    // Summary
    double total_time = std::chrono::duration<double>(t3 - t0).count();
    std::cout << "\n" << std::string(50, '=') << std::endl;
    std::cout << "SUMMARY (" << label << ")" << std::endl;
    std::cout << std::string(50, '=') << std::endl;
    std::cout << "  Phase 1 (SVM):    E = " << std::setprecision(10) << E_svm
              << "  (error = " << std::scientific << (E_svm - E_exact)
              << std::defaultfloat << ")" << std::endl;
    std::cout << "  Phase 2 (TDVP):   E = " << std::setprecision(10) << E_final
              << "  (error = " << std::scientific << (E_final - E_exact)
              << std::defaultfloat << ")" << std::endl;
    std::cout << "  Target:           E = " << std::setprecision(10) << E_exact << std::endl;
    std::cout << "  Total time: " << std::fixed << std::setprecision(1) << total_time << "s" << std::endl;
}

static void run_phase3_tdvp_delta() {
    HamiltonianTerms terms;
    terms.kinetic  = true;
    terms.harmonic = true;
    terms.delta    = true;
    terms.gaussian = false;
    terms.kicking  = false;

    run_svm_tdvp("2-particle delta contact", terms, 1.3067455);
}

static void run_phase3_tdvp_gaussian() {
    HamiltonianTerms terms;
    terms.kinetic  = true;
    terms.harmonic = true;
    terms.delta    = false;
    terms.gaussian = true;
    terms.kicking  = false;

    run_svm_tdvp("2-particle Gaussian interaction", terms, 1.5266998310);
}

static void run_phase3_tdvp_kicking() {
    HamiltonianTerms terms;
    terms.kinetic  = true;
    terms.harmonic = true;
    terms.delta    = false;
    terms.gaussian = false;
    terms.kicking  = true;

    // No known exact value; use a placeholder
    run_svm_tdvp("2-particle kicking term", terms, 0.0);
}

int main(int argc, char* argv[]) {
    std::cout << std::setprecision(18);

    std::vector<BasisParams> basis;
    int N = 2, basis_n = 2;

    if (argc >= 5 && std::string(argv[1]) == "--csv") {
        std::string filename = argv[2];
        N = std::stoi(argv[3]);
        basis_n = std::stoi(argv[4]);
        basis = load_basis_from_csv(filename, N, basis_n);
        if (basis.empty()) return 1;
    } else {
        for (int t = 0; t < basis_n; t++) {
            basis.push_back(BasisParams::randoman(N, t, t));
        }
    }

    std::cout << "N=" << N << ", K=" << basis_n << std::endl;

    run_phase1(basis, N);

    if (basis_n >= 2) {
        run_phase2(basis, N);
    }

    run_phase3_gradient(basis, N);

    // If invoked with --tdvp flag, run TDVP evolution
    bool run_tdvp = false;
    bool tdvp_only = false;
    bool run_delta = false;
    bool run_gaussian = false;
    bool run_kicking = false;
    for (int i = 1; i < argc; i++) {
        if (std::string(argv[i]) == "--tdvp") run_tdvp = true;
        if (std::string(argv[i]) == "--tdvp-only") tdvp_only = true;
        if (std::string(argv[i]) == "--delta") run_delta = true;
        if (std::string(argv[i]) == "--gaussian") run_gaussian = true;
        if (std::string(argv[i]) == "--kicking") run_kicking = true;
    }
    if (run_tdvp || tdvp_only) {
        run_phase3_tdvp();
    }
    if (run_delta) {
        run_phase3_tdvp_delta();
    }
    if (run_gaussian) {
        run_phase3_tdvp_gaussian();
    }
    if (run_kicking) {
        run_phase3_tdvp_kicking();
    }

    return 0;
}
