#include "basis_params.hpp"
#include "hamiltonian.hpp"
#include "derivatives.hpp"
#include "hamiltonian_gradient.hpp"
#include "tdvp_solver.hpp"
#include "svm.hpp"
#include "interaction_kernels.hpp"
#include "pair_cache.hpp"
#include "kicked_evolution.hpp"
#include "observables.hpp"
#include <iostream>
#include <iomanip>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <chrono>

using namespace ecg1d;

// Read basis function parameters from a CSV file generated by the Python script.
// Format: one line per complex number, "real,imag"
// File structure: for each basis function: u(1), A(N*N), B(N*N), R(N), name(1)
static std::vector<BasisParams> load_basis_from_csv(const std::string& filename, int N, int basis_n) {
    std::ifstream fin(filename);
    if (!fin.is_open()) {
        std::cerr << "Cannot open " << filename << std::endl;
        return {};
    }

    auto read_complex = [&]() -> Cd {
        std::string line;
        std::getline(fin, line);
        std::stringstream ss(line);
        double re, im;
        char comma;
        ss >> re >> comma >> im;
        return Cd(re, im);
    };

    auto read_int = [&]() -> int {
        std::string line;
        std::getline(fin, line);
        return std::stoi(line);
    };

    std::vector<BasisParams> basis(basis_n);
    for (int k = 0; k < basis_n; k++) {
        basis[k].u = read_complex();
        basis[k].A = MatrixXcd(N, N);
        for (int i = 0; i < N; i++)
            for (int j = 0; j < N; j++)
                basis[k].A(i, j) = read_complex();
        basis[k].B = MatrixXcd(N, N);
        for (int i = 0; i < N; i++)
            for (int j = 0; j < N; j++)
                basis[k].B(i, j) = read_complex();
        basis[k].R = VectorXcd(N);
        for (int i = 0; i < N; i++)
            basis[k].R(i) = read_complex();
        basis[k].name = read_int();
    }
    return basis;
}

static void print_complex(const std::string& label, Cd v) {
    std::cout << label << ": " << v.real() << " + " << v.imag() << "i" << std::endl;
}

static void run_phase1(const std::vector<BasisParams>& basis, int N) {
    std::cout << "=== Phase 1: Functionals ===" << std::endl;

    Cd S = overlap(basis);
    print_complex("Overlap", S);

    Cd T = kinetic_energy_functional(basis);
    print_complex("Kinetic", T);

    Cd V = Harmonic_functional(basis);
    print_complex("Harmonic", V);

    if (N >= 2) {
        Cd D = Delta_contact_functional(basis);
        print_complex("Delta", D);

        Cd G = Gaussian_interaction_functional(basis);
        print_complex("Gaussian", G);
    }

    Cd K_val = kicking_term_functional(basis);
    print_complex("Kicking", K_val);

    Cd E = (T + V) / S;
    print_complex("E(T+V)/S", E);
}

static void run_phase2(const std::vector<BasisParams>& basis, int N) {
    std::cout << "\n=== Phase 2: Derivatives ===" << std::endl;

    int name0 = basis[0].name;
    int name1 = basis[1].name;

    // partial_z_first tests
    Cd v;

    v = partial_z_first(1, true, basis, name0, 0, 0);
    print_complex("pz_first(1,T," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_first(1, false, basis, name0, 0, 0);
    print_complex("pz_first(1,F," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_first(2, true, basis, name0, 0, 0);
    print_complex("pz_first(2,T," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_first(2, false, basis, name0, 0, 0);
    print_complex("pz_first(2,F," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_first(3, true, basis, name0, 0, 0);
    print_complex("pz_first(3,T," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_first(3, false, basis, name1, 0, 0);
    print_complex("pz_first(3,F," + std::to_string(name1) + ",0,0)", v);

    v = partial_z_first(4, true, basis, name0, 0, 0);
    print_complex("pz_first(4,T," + std::to_string(name0) + ",0,0)", v);

    if (N >= 2) {
        v = partial_z_first(4, true, basis, name0, 0, 1);
        print_complex("pz_first(4,T," + std::to_string(name0) + ",0,1)", v);
    }

    // partial_z_second tests
    v = partial_z_second(2, 2, basis, name0, 0, 0, name0, 0, 0);
    print_complex("pz_second(2,2," + std::to_string(name0) + ",0,0," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_second(1, 1, basis, name0, 0, 0, name0, 0, 0);
    print_complex("pz_second(1,1," + std::to_string(name0) + ",0,0," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_second(1, 2, basis, name0, 0, 0, name0, 0, 0);
    print_complex("pz_second(1,2," + std::to_string(name0) + ",0,0," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_second(3, 2, basis, name0, 0, 0, name0, 0, 0);
    print_complex("pz_second(3,2," + std::to_string(name0) + ",0,0," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_second(4, 2, basis, name0, 0, 0, name0, 0, 0);
    print_complex("pz_second(4,2," + std::to_string(name0) + ",0,0," + std::to_string(name0) + ",0,0)", v);

    if (N >= 2) {
        v = partial_z_second(4, 2, basis, name0, 0, 1, name0, 0, 0);
        print_complex("pz_second(4,2," + std::to_string(name0) + ",0,1," + std::to_string(name0) + ",0,0)", v);
    }

    // calculate_C tests
    v = calculate_C(1, name0, 0, 0, 1, name0, 0, 0, basis);
    print_complex("C(1," + std::to_string(name0) + ",0,0,1," + std::to_string(name0) + ",0,0)", v);

    v = calculate_C(2, name0, 0, 0, 2, name0, 0, 0, basis);
    print_complex("C(2," + std::to_string(name0) + ",0,0,2," + std::to_string(name0) + ",0,0)", v);

    v = calculate_C(3, name0, 0, 0, 2, name0, 0, 0, basis);
    print_complex("C(3," + std::to_string(name0) + ",0,0,2," + std::to_string(name0) + ",0,0)", v);

    v = calculate_C(4, name0, 0, 0, 2, name0, 0, 0, basis);
    print_complex("C(4," + std::to_string(name0) + ",0,0,2," + std::to_string(name0) + ",0,0)", v);
}

static void run_phase3_gradient(const std::vector<BasisParams>& basis, int N) {
    std::cout << "\n=== Phase 3: Hamiltonian Gradients ===" << std::endl;

    int name0 = basis[0].name;
    int name1 = (basis.size() > 1) ? basis[1].name : name0;
    std::string sn0 = std::to_string(name0);
    std::string sn1 = std::to_string(name1);

    auto rf_str = [](bool r) { return r ? "T" : "F"; };

    // Test all Hamiltonian gradient terms for a1={1,2,3}, Real={T,F}
    for (int a1 : {1, 2, 3}) {
        int a2 = name0;
        for (bool real_flag : {true, false}) {
            std::string tag = "(" + std::to_string(a1) + "," + rf_str(real_flag) + "," + sn0 + ",0,0)";

            Cd gT = calculate_Hamiltonian_kinetic_partial(a1, a2, 0, 0, real_flag, basis);
            print_complex("gKinetic" + tag, gT);

            Cd gW = calculate_Hamiltonian_harmonic_partial(a1, a2, 0, 0, real_flag, basis);
            print_complex("gHarmonic" + tag, gW);

            if (N >= 2) {
                Cd gD = calculate_Hamiltonian_delta_partial(a1, a2, 0, 0, real_flag, basis);
                print_complex("gDelta" + tag, gD);

                Cd gG = calculate_Hamiltonian_gaussian_partial(a1, a2, 0, 0, real_flag, basis);
                print_complex("gGaussian" + tag, gG);
            }

            Cd gK = calculate_Hamiltonian_kicking_partial(a1, a2, 0, 0, real_flag, basis);
            print_complex("gKicking" + tag, gK);
        }
    }

    // Also test with a different basis index (name1) for a1=2,3
    if (basis.size() > 1) {
        for (int a1 : {2, 3}) {
            for (bool real_flag : {true, false}) {
                std::string tag = "(" + std::to_string(a1) + "," + rf_str(real_flag) + "," + sn1 + ",0,0)";

                Cd gT = calculate_Hamiltonian_kinetic_partial(a1, name1, 0, 0, real_flag, basis);
                print_complex("gKinetic" + tag, gT);

                Cd gW = calculate_Hamiltonian_harmonic_partial(a1, name1, 0, 0, real_flag, basis);
                print_complex("gHarmonic" + tag, gW);

                if (N >= 2) {
                    Cd gD = calculate_Hamiltonian_delta_partial(a1, name1, 0, 0, real_flag, basis);
                    print_complex("gDelta" + tag, gD);

                    Cd gG = calculate_Hamiltonian_gaussian_partial(a1, name1, 0, 0, real_flag, basis);
                    print_complex("gGaussian" + tag, gG);
                }

                Cd gK = calculate_Hamiltonian_kicking_partial(a1, name1, 0, 0, real_flag, basis);
                print_complex("gKicking" + tag, gK);
            }
        }
    }

    // Test a1=4 (A matrix derivative) if N >= 2
    if (N >= 2) {
        for (bool real_flag : {true, false}) {
            std::string tag = "(4," + std::string(rf_str(real_flag)) + "," + sn0 + ",0,0)";

            Cd gT = calculate_Hamiltonian_kinetic_partial(4, name0, 0, 0, real_flag, basis);
            print_complex("gKinetic" + tag, gT);

            Cd gW = calculate_Hamiltonian_harmonic_partial(4, name0, 0, 0, real_flag, basis);
            print_complex("gHarmonic" + tag, gW);

            Cd gD = calculate_Hamiltonian_delta_partial(4, name0, 0, 0, real_flag, basis);
            print_complex("gDelta" + tag, gD);

            Cd gG = calculate_Hamiltonian_gaussian_partial(4, name0, 0, 0, real_flag, basis);
            print_complex("gGaussian" + tag, gG);

            Cd gK = calculate_Hamiltonian_kicking_partial(4, name0, 0, 0, real_flag, basis);
            print_complex("gKicking" + tag, gK);

            // Also test (0,1) for off-diagonal
            std::string tag2 = "(4," + std::string(rf_str(real_flag)) + "," + sn0 + ",0,1)";

            gT = calculate_Hamiltonian_kinetic_partial(4, name0, 0, 1, real_flag, basis);
            print_complex("gKinetic" + tag2, gT);

            gW = calculate_Hamiltonian_harmonic_partial(4, name0, 0, 1, real_flag, basis);
            print_complex("gHarmonic" + tag2, gW);

            gD = calculate_Hamiltonian_delta_partial(4, name0, 0, 1, real_flag, basis);
            print_complex("gDelta" + tag2, gD);

            gG = calculate_Hamiltonian_gaussian_partial(4, name0, 0, 1, real_flag, basis);
            print_complex("gGaussian" + tag2, gG);

            gK = calculate_Hamiltonian_kicking_partial(4, name0, 0, 1, real_flag, basis);
            print_complex("gKicking" + tag2, gK);
        }
    }
}

static void run_phase3_tdvp() {
    std::cout << "\n=== Phase 3: TDVP Evolution (1-particle harmonic) ===" << std::endl;

    // Same initial conditions as Python Verification_One_Particle_Harmonic_1.py
    int N = 1;
    std::vector<BasisParams> basis;
    basis.push_back(BasisParams::from_arrays(
        Cd(1.0, 0.0),
        (MatrixXcd(1,1) << Cd(0.1, 0.1)).finished(),
        (MatrixXcd(1,1) << Cd(0.3, 0.1)).finished(),
        (VectorXcd(1) << Cd(0.2, 0.1)).finished(),
        0
    ));

    int basis_n = static_cast<int>(basis.size());

    // Build alpha_z_list matching Python
    std::vector<AlphaIndex> alpha_z_list;
    // u parameters (a1=1)
    for (int i = 0; i < basis_n; i++)
        alpha_z_list.push_back({1, i, 0, 0});
    // B parameters (a1=2)
    for (int i = 0; i < basis_n; i++)
        for (int j = 0; j < N; j++)
            alpha_z_list.push_back({2, i, j, 0});
    // R parameters (a1=3)
    for (int i = 0; i < basis_n; i++)
        for (int j = 0; j < N; j++)
            alpha_z_list.push_back({3, i, j, 0});

    auto terms = HamiltonianTerms::kinetic_harmonic();

    // Compare gradients with Python
    std::cout << "--- Gradient comparison (1-particle, kinetic+harmonic) ---" << std::endl;
    for (int a1 : {2, 3}) {
        for (bool rf : {true, false}) {
            Cd gT = calculate_Hamiltonian_kinetic_partial(a1, 0, 0, 0, rf, basis);
            Cd gW = calculate_Hamiltonian_harmonic_partial(a1, 0, 0, 0, rf, basis);
            std::string rl = rf ? "Real" : "Imag";
            std::cout << "a1=" << a1 << " " << rl
                      << ": gT=" << gT << ", gW=" << gW << ", total=" << (gT+gW) << std::endl;
        }
    }

    Cd E0 = compute_total_energy(basis, terms);
    std::cout << "Initial E = " << E0.real() << std::endl;
    std::cout << "Expected ground state E = 0.5 (hbar*omega/2)" << std::endl;

    evolution(alpha_z_list, basis, 1e-3, 5000, 1e-12, terms);

    Cd E_final = compute_total_energy(basis, terms);
    std::cout << "Final E = " << std::setprecision(10) << E_final.real() << std::endl;
    std::cout << "Error from 0.5 = " << std::scientific << (E_final.real() - 0.5) << std::endl;
}

// Build alpha_z_list for TDVP (including A matrix parameters for N>=2)
static std::vector<AlphaIndex> build_alpha_z_list(int basis_n, int N) {
    std::vector<AlphaIndex> alpha_z_list;
    // u parameters (a1=1)
    for (int i = 0; i < basis_n; i++)
        alpha_z_list.push_back({1, i, 0, 0});
    // B parameters (a1=2)
    for (int i = 0; i < basis_n; i++)
        for (int j = 0; j < N; j++)
            alpha_z_list.push_back({2, i, j, 0});
    // R parameters (a1=3)
    for (int i = 0; i < basis_n; i++)
        for (int j = 0; j < N; j++)
            alpha_z_list.push_back({3, i, j, 0});
    // A parameters (a1=4), upper triangle only
    for (int i = 0; i < basis_n; i++)
        for (int j = 0; j < N; j++)
            for (int k = j; k < N; k++)
                alpha_z_list.push_back({4, i, j, k});

    return alpha_z_list;
}

// Run the full SVM + stochastic refinement + TDVP pipeline
static void run_svm_tdvp(const std::string& label,
                          const HamiltonianTerms& terms,
                          double E_exact,
                          int K_max = 5, int svm_trials = 5000,
                          int refine_trials = 500, int refine_rounds = 10,
                          int tdvp_steps = 300,
                          double E_lower_bound = 0.0) {
    int N = 2;
    auto t0 = std::chrono::steady_clock::now();

    // Phase 1: SVM basis construction
    std::cout << "\n=== SVM + TDVP: " << label << " ===" << std::endl;
    std::cout << "Target E = " << std::setprecision(10) << E_exact << std::endl;
    std::cout << "\n--- Phase 1: Stochastic Variational Method ---" << std::endl;

    auto svm = svm_build_basis(N, K_max, svm_trials, terms, 42, E_lower_bound);
    double E_svm = lowest_energy(svm.H, svm.S);
    auto t1 = std::chrono::steady_clock::now();
    double dt1 = std::chrono::duration<double>(t1 - t0).count();
    std::cout << "SVM result: E = " << std::setprecision(10) << E_svm
              << "  (error = " << std::scientific << (E_svm - E_exact)
              << std::defaultfloat << ")" << std::endl;
    std::cout << "Phase 1 time: " << std::fixed << std::setprecision(1) << dt1 << "s" << std::endl;

    // Check A symmetry after SVM
    {
        double max_asym = 0;
        int worst_k = -1;
        for (int k = 0; k < (int)svm.basis.size(); k++) {
            double asym = (svm.basis[k].A - svm.basis[k].A.transpose()).norm();
            if (asym > max_asym) { max_asym = asym; worst_k = k; }
        }
        std::cout << "A symmetry after SVM: max ||A-A^T|| = " << std::scientific << max_asym
                  << " (basis[" << worst_k << "])" << std::defaultfloat << std::endl;
    }

    // Phase 1.5: Stochastic refinement (A3: re-enabled)
    PermutationSet perms = PermutationSet::generate(N);
    SvmResult refined = svm;
    double E_refine = E_svm;
    auto t2 = t1;

    if (refine_rounds > 0) {
        std::cout << "\n--- Phase 1.5: Stochastic Refinement ---" << std::endl;
        refined = stochastic_refine(svm.basis, svm.H, svm.S,
                                     perms, N, terms,
                                     refine_trials, refine_rounds, 123,
                                     E_lower_bound);
        E_refine = lowest_energy(refined.H, refined.S);
        t2 = std::chrono::steady_clock::now();
        double dt15 = std::chrono::duration<double>(t2 - t1).count();
        std::cout << "Refine result (stored H/S): E = " << std::setprecision(10) << E_refine
                  << "  (error = " << std::scientific << (E_refine - E_exact)
                  << std::defaultfloat << ")" << std::endl;

        // Diagnostic: compute energy components separately
        {
            HamiltonianTerms t_only  = {true, false, false, false, false};
            HamiltonianTerms v_only  = {false, true, false, false, false};
            HamiltonianTerms g_only  = {false, false, false, true, false};
            HamiltonianTerms tv_only = {true, true, false, false, false};

            auto [H_t, S_t] = build_HS(refined.basis, perms, t_only);
            auto [H_v, S_v] = build_HS(refined.basis, perms, v_only);
            auto [H_g, S_g] = build_HS(refined.basis, perms, g_only);
            auto [H_tv, S_tv] = build_HS(refined.basis, perms, tv_only);
            auto [H_full, S_full] = build_HS(refined.basis, perms, terms);

            // Use the eigenvector from the full problem to compute each component
            set_u_from_eigenvector(refined.basis, H_full, S_full);

            // Compute <ψ|O|ψ> / <ψ|ψ> for each operator
            // u is stored in refined.basis[i].u
            int nb = static_cast<int>(refined.basis.size());
            VectorXcd u(nb);
            for (int i = 0; i < nb; i++) u(i) = refined.basis[i].u;

            // S is the same for all terms (overlap doesn't depend on Hamiltonian)
            Cd norm  = (u.adjoint() * S_full * u)(0);
            Cd e_kin = (u.adjoint() * H_t * u)(0) / norm;
            Cd e_har = (u.adjoint() * H_v * u)(0) / norm;
            Cd e_int = (u.adjoint() * H_g * u)(0) / norm;
            Cd e_tv  = (u.adjoint() * H_tv * u)(0) / norm;
            Cd e_tot = (u.adjoint() * H_full * u)(0) / norm;

            // Also verify: eigenvalue from full diag should match
            double E_eigenval = lowest_energy(H_full, S_full);
            // Check linearity: H_full should = H_t + H_v + H_g
            double H_sum_diff = (H_full - H_t - H_v - H_g).norm();
            // Check S consistency
            double S_diff_tv = (S_t - S_full).norm();
            double S_diff_g = (S_g - S_full).norm();

            std::cout << "  Energy decomposition of refine result:" << std::endl;
            std::cout << "    <T>     = " << std::setprecision(10) << e_kin.real() << std::endl;
            std::cout << "    <V_har> = " << e_har.real() << std::endl;
            std::cout << "    <V_int> = " << e_int.real() << std::endl;
            std::cout << "    <T+V>   = " << e_tv.real() << std::endl;
            std::cout << "    <Total> = " << e_tot.real() << std::endl;
            std::cout << "    norm    = " << norm.real() << std::endl;
            std::cout << "    E_eigenval = " << E_eigenval << std::endl;
            std::cout << "    ||H_full - H_t - H_v - H_g|| = " << std::scientific << H_sum_diff << std::endl;
            std::cout << "    ||S_t - S_full|| = " << S_diff_tv << std::endl;
            std::cout << "    ||S_g - S_full|| = " << S_diff_g << std::defaultfloat << std::endl;

            // Print H_g eigenvalues to see if it has negative eigenvalues
            MatrixXcd Hg_herm = 0.5 * (H_g + H_g.adjoint());
            Eigen::SelfAdjointEigenSolver<MatrixXcd> es_hg(Hg_herm);
            std::cout << "    H_g eigenvalues: ";
            for (int i = 0; i < std::min(5, nb); i++)
                std::cout << std::setprecision(6) << es_hg.eigenvalues()(i) << " ";
            std::cout << "..." << std::endl;

            // Check: are basis function params actually real?
            double max_imag = 0;
            for (int i = 0; i < nb; i++) {
                max_imag = std::max(max_imag, refined.basis[i].A.imag().cwiseAbs().maxCoeff());
                max_imag = std::max(max_imag, refined.basis[i].B.imag().cwiseAbs().maxCoeff());
                max_imag = std::max(max_imag, refined.basis[i].R.imag().cwiseAbs().maxCoeff());
            }
            std::cout << "    max |Im| in basis params = " << std::scientific << max_imag << std::defaultfloat << std::endl;

            // Per-permutation Hermitian symmetry test for pair (0,1)
            std::cout << "    Per-permutation test (pair 0,1), gaussian only:" << std::endl;
            for (int p = 0; p < perms.SN; p++) {
                PairCache c_ab = PairCache::build(refined.basis[0], refined.basis[1], perms.matrices[p]);
                PairCache c_ba = PairCache::build(refined.basis[1], refined.basis[0], perms.matrices[p]);

                Cd mg_ab = c_ab.M_G, mg_ba = c_ba.M_G;
                Cd gk_ab = compute_H_Mijab(c_ab, 0, 1);
                Cd gk_ba = compute_H_Mijab(c_ba, 0, 1);

                std::cout << "      P=" << p
                          << "  M_G: " << std::setprecision(10) << mg_ab.real()
                          << " vs " << mg_ba.real()
                          << "  diff=" << std::scientific << std::abs(mg_ab - mg_ba)
                          << std::endl;
                std::cout << "        kernel: " << std::setprecision(10) << std::defaultfloat << gk_ab.real()
                          << " vs " << gk_ba.real()
                          << "  diff=" << std::scientific << std::abs(gk_ab - gk_ba)
                          << std::endl;
                std::cout << "        M_G*k:  " << std::defaultfloat << std::setprecision(10) << (mg_ab*gk_ab).real()
                          << " vs " << (mg_ba*gk_ba).real()
                          << "  diff=" << std::scientific << std::abs(mg_ab*gk_ab - mg_ba*gk_ba)
                          << std::defaultfloat << std::endl;

                // Detailed: K_inv, mu, h, p for this permutation
                Cd h_ab_val = c_ab.K_inv(0,0) + c_ab.K_inv(1,1) - 2.0*c_ab.K_inv(0,1);
                Cd h_ba_val = c_ba.K_inv(0,0) + c_ba.K_inv(1,1) - 2.0*c_ba.K_inv(0,1);
                Cd p_ab_val = c_ab.mu(0) - c_ab.mu(1);
                Cd p_ba_val = c_ba.mu(0) - c_ba.mu(1);
                std::cout << "        h:  " << std::setprecision(10) << h_ab_val.real()
                          << " vs " << h_ba_val.real() << std::endl;
                std::cout << "        p:  " << p_ab_val.real()
                          << " vs " << p_ba_val.real() << std::endl;
                std::cout << "        K_inv(0,0): " << c_ab.K_inv(0,0).real() << " vs " << c_ba.K_inv(0,0).real() << std::endl;
                std::cout << "        K_inv(1,1): " << c_ab.K_inv(1,1).real() << " vs " << c_ba.K_inv(1,1).real() << std::endl;
                std::cout << "        K_inv(0,1): " << c_ab.K_inv(0,1).real() << " vs " << c_ba.K_inv(0,1).real() << std::endl;
                std::cout << "        mu(0): " << c_ab.mu(0).real() << " vs " << c_ba.mu(0).real() << std::endl;
                std::cout << "        mu(1): " << c_ab.mu(1).real() << " vs " << c_ba.mu(1).real() << std::endl;
                std::cout << "        K(0,0): " << c_ab.K(0,0).real() << " vs " << c_ba.K(0,0).real() << std::endl;
                std::cout << "        K(1,1): " << c_ab.K(1,1).real() << " vs " << c_ba.K(1,1).real() << std::endl;
                std::cout << "        K(0,1): " << c_ab.K(0,1).real() << " vs " << c_ba.K(0,1).real() << std::endl;
                std::cout << "        K(1,0): " << c_ab.K(1,0).real() << " vs " << c_ba.K(1,0).real() << std::endl;
                if (p == 0) {
                    // Print A matrices of basis[0] and basis[1]
                    auto& b0 = refined.basis[0]; auto& b1 = refined.basis[1];
                    std::cout << "        basis[0].A: [[" << b0.A(0,0).real() << "," << b0.A(0,1).real()
                              << "],[" << b0.A(1,0).real() << "," << b0.A(1,1).real() << "]]" << std::endl;
                    std::cout << "        basis[1].A: [[" << b1.A(0,0).real() << "," << b1.A(0,1).real()
                              << "],[" << b1.A(1,0).real() << "," << b1.A(1,1).real() << "]]" << std::endl;
                    std::cout << "        basis[0].B diag: " << b0.B(0,0).real() << "," << b0.B(1,1).real() << std::endl;
                    std::cout << "        basis[1].B diag: " << b1.B(0,0).real() << "," << b1.B(1,1).real() << std::endl;
                    double asym0 = std::abs(b0.A(0,1).real() - b0.A(1,0).real());
                    double asym1 = std::abs(b1.A(0,1).real() - b1.A(1,0).real());
                    std::cout << "        |A(0,1)-A(1,0)|: basis0=" << std::scientific << asym0
                              << " basis1=" << asym1 << std::defaultfloat << std::endl;
                }
            }
        }

        std::cout << "Phase 1.5 time: " << std::fixed << std::setprecision(1) << dt15 << "s" << std::endl;
    }

    // Phase 2: TDVP refinement (with SolverConfig)
    std::cout << "\n--- Phase 2: TDVP refinement ---" << std::endl;
    set_u_from_eigenvector(refined.basis, refined.H, refined.S);

    int basis_n = static_cast<int>(refined.basis.size());
    auto alpha_z_list = build_alpha_z_list(basis_n, N);

    SolverConfig config;
    config.lambda_C          = 1e-8;
    config.rcond             = 1e-4;
    config.resolve_u         = true;
    config.dtao_grow         = 1.5;
    config.dtao_max          = 10.0;
    config.energy_tol        = 1e-12;
    config.stagnation_window = 50;
    config.adaptive_lambda   = true;
    config.lambda_max        = 1e-4;

    std::cout << "TDVP config: dtao_max=" << config.dtao_max
              << ", energy_tol=" << std::scientific << config.energy_tol
              << ", stagnation_window=" << config.stagnation_window
              << ", adaptive_lambda=" << config.adaptive_lambda
              << std::defaultfloat << std::endl;

    evolution(alpha_z_list, refined.basis, 1, tdvp_steps, 1e-10, terms, config, &perms);

    // Print energy error at phase transition
    {
        auto [H_post, S_post] = build_HS(refined.basis, perms, terms);
        double E_post = lowest_energy(H_post, S_post);
        std::cout << "Post-TDVP eigenvalue E = " << std::setprecision(10) << E_post
                  << "  (error = " << std::scientific << (E_post - E_exact)
                  << std::defaultfloat << ")" << std::endl;
    }

    // Final energy from eigenvalue approach (with variance diagnostic)
    auto [H_final, S_final] = build_HS(refined.basis, perms, terms);
    auto final_res = lowest_energy_full(H_final, S_final);
    double E_final = final_res.energy;
    auto t3 = std::chrono::steady_clock::now();
    double dt3 = std::chrono::duration<double>(t3 - t2).count();

    std::cout << "\nPhase 2 time: " << std::fixed << std::setprecision(1) << dt3 << "s" << std::endl;
    if (final_res.variance >= 0) {
        double sigma = std::sqrt(std::max(0.0, final_res.variance));
        std::cout << "Energy variance sigma = " << std::scientific << sigma
                  << "  (sigma^2 = " << final_res.variance << ")"
                  << std::defaultfloat << std::endl;
    }

    // Summary
    double total_time = std::chrono::duration<double>(t3 - t0).count();
    std::cout << "\n" << std::string(50, '=') << std::endl;
    std::cout << "SUMMARY (" << label << ")" << std::endl;
    std::cout << std::string(50, '=') << std::endl;
    std::cout << "  Phase 1 (SVM):    E = " << std::setprecision(10) << E_svm
              << "  (error = " << std::scientific << (E_svm - E_exact)
              << std::defaultfloat << ")" << std::endl;
    if (refine_rounds > 0) {
        std::cout << "  Phase 1.5 (Ref):  E = " << std::setprecision(10) << E_refine
                  << "  (error = " << std::scientific << (E_refine - E_exact)
                  << std::defaultfloat << ")" << std::endl;
    }
    std::cout << "  Phase 2 (TDVP):   E = " << std::setprecision(10) << E_final
              << "  (error = " << std::scientific << (E_final - E_exact)
              << std::defaultfloat << ")" << std::endl;
    std::cout << "  Target:           E = " << std::setprecision(10) << E_exact << std::endl;
    std::cout << "  Total time: " << std::fixed << std::setprecision(1) << total_time << "s" << std::endl;
}

static void run_phase3_tdvp_delta() {
    HamiltonianTerms terms;
    terms.kinetic  = true;
    terms.harmonic = true;
    terms.delta    = true;
    terms.gaussian = false;
    terms.kicking  = false;

    run_svm_tdvp("2-particle delta contact", terms, 1.3067455,
                 /*K_max=*/15, /*svm_trials=*/5000,
                 /*refine_trials=*/500, /*refine_rounds=*/10,
                 /*tdvp_steps=*/1000,
                 /*E_lower_bound=*/1.0);
}

static void run_phase3_tdvp_gaussian() {
    HamiltonianTerms terms;
    terms.kinetic  = true;
    terms.harmonic = true;
    terms.delta    = false;
    terms.gaussian = true;
    terms.kicking  = false;

    run_svm_tdvp("2-particle Gaussian interaction", terms, 1.5266998310,
                 /*K_max=*/20, /*svm_trials=*/5000,
                 /*refine_trials=*/500, /*refine_rounds=*/10,
                 /*tdvp_steps=*/1000,
                 /*E_lower_bound=*/1.0);
}

static void run_phase3_tdvp_kicking() {
    HamiltonianTerms terms;
    terms.kinetic  = true;
    terms.harmonic = true;
    terms.delta    = false;
    terms.gaussian = false;
    terms.kicking  = true;

    // No known exact value; use a placeholder
    run_svm_tdvp("2-particle kicking term", terms, 0.0);
}

static void run_kicked_evolution_test() {
    std::cout << "\n=== Kicked Real-Time Evolution (N=2, delta interaction) ===" << std::endl;

    int N = 2;
    int K_max = 15;

    // Build basis via SVM with kinetic + harmonic + delta
    HamiltonianTerms terms_free;
    terms_free.kinetic  = true;
    terms_free.harmonic = true;
    terms_free.delta    = true;
    terms_free.gaussian = false;
    terms_free.kicking  = false;

    std::cout << "--- Building basis with SVM ---" << std::endl;
    double E_lower_kicked = N * 0.5;  // harmonic trap lower bound
    auto svm = svm_build_basis(N, K_max, 5000, terms_free, 42, E_lower_kicked);
    double E_svm = lowest_energy(svm.H, svm.S);
    std::cout << "SVM ground state E = " << std::setprecision(10) << E_svm << std::endl;

    // Refine basis
    PermutationSet perms = PermutationSet::generate(N);
    auto refined = stochastic_refine(svm.basis, svm.H, svm.S,
                                      perms, N, terms_free, 500, 10, 123,
                                      E_lower_kicked);
    double E_ref = lowest_energy(refined.H, refined.S);
    std::cout << "Refined ground state E = " << std::setprecision(10) << E_ref << std::endl;

    // Set u from eigenvector
    set_u_from_eigenvector(refined.basis, refined.H, refined.S);

    // TDVP imaginary-time polish
    int basis_n = static_cast<int>(refined.basis.size());
    auto alpha_z_list = build_alpha_z_list(basis_n, N);

    SolverConfig config;
    config.lambda_C  = 1e-8;
    config.rcond     = 1e-4;
    config.resolve_u = true;
    config.dtao_grow = 1.5;

    std::cout << "\n--- Imaginary-time TDVP polish ---" << std::endl;
    evolution(alpha_z_list, refined.basis, 1, 100, 1e-10, terms_free, config, &perms);

    // Now do kicked real-time evolution
    HamiltonianTerms terms_kick = terms_free;
    terms_kick.kicking = true;

    KickParams kick_params;
    kick_params.T_period   = 1.0;
    kick_params.T_pulse    = 0.0;   // ideal delta kick
    kick_params.kappa_kick = 1.0;
    kick_params.k_L_kick   = 0.5;
    kick_params.n_kicks    = 10;

    SolverConfig rt_config;
    rt_config.lambda_C  = 1e-8;
    rt_config.rcond     = 1e-4;
    rt_config.resolve_u = true;

    double dt_step = 0.01;

    std::cout << "\n--- Real-time kicked evolution ---" << std::endl;
    std::cout << "T_period=" << kick_params.T_period
              << ", n_kicks=" << kick_params.n_kicks
              << ", dt=" << dt_step << std::endl;

    auto obs = kicked_evolution(refined.basis, alpha_z_list, kick_params,
                                 dt_step, terms_free, terms_kick,
                                 rt_config, &perms);

    // Summary
    std::cout << "\n--- Observable summary ---" << std::endl;
    std::cout << std::setw(6) << "kick" << std::setw(12) << "time"
              << std::setw(16) << "energy" << std::setw(16) << "kinetic"
              << std::setw(12) << "overlap" << std::endl;
    for (size_t i = 0; i < obs.size(); i++) {
        std::cout << std::setw(6) << i
                  << std::setw(12) << std::setprecision(4) << obs[i].time
                  << std::setw(16) << std::setprecision(8) << obs[i].energy
                  << std::setw(16) << std::setprecision(8) << obs[i].kinetic_energy
                  << std::setw(12) << std::setprecision(6) << obs[i].overlap_norm
                  << std::endl;
    }
}

int main(int argc, char* argv[]) {
    std::cout << std::setprecision(18);

    std::vector<BasisParams> basis;
    int N = 2, basis_n = 2;

    if (argc >= 5 && std::string(argv[1]) == "--csv") {
        std::string filename = argv[2];
        N = std::stoi(argv[3]);
        basis_n = std::stoi(argv[4]);
        basis = load_basis_from_csv(filename, N, basis_n);
        if (basis.empty()) return 1;
    } else {
        for (int t = 0; t < basis_n; t++) {
            basis.push_back(BasisParams::randoman(N, t, t));
        }
    }

    std::cout << "N=" << N << ", K=" << basis_n << std::endl;

    run_phase1(basis, N);

    if (basis_n >= 2) {
        run_phase2(basis, N);
    }

    run_phase3_gradient(basis, N);

    // If invoked with --tdvp flag, run TDVP evolution
    bool run_tdvp = false;
    bool tdvp_only = false;
    bool run_delta = false;
    bool run_gaussian = false;
    bool run_kicking = false;
    bool run_kicked = false;
    for (int i = 1; i < argc; i++) {
        if (std::string(argv[i]) == "--tdvp") run_tdvp = true;
        if (std::string(argv[i]) == "--tdvp-only") tdvp_only = true;
        if (std::string(argv[i]) == "--delta") run_delta = true;
        if (std::string(argv[i]) == "--gaussian") run_gaussian = true;
        if (std::string(argv[i]) == "--kicking") run_kicking = true;
        if (std::string(argv[i]) == "--kicked") run_kicked = true;
    }
    if (run_tdvp || tdvp_only) {
        run_phase3_tdvp();
    }
    if (run_delta) {
        run_phase3_tdvp_delta();
    }
    if (run_gaussian) {
        run_phase3_tdvp_gaussian();
    }
    if (run_kicking) {
        run_phase3_tdvp_kicking();
    }
    if (run_kicked) {
        run_kicked_evolution_test();
    }

    return 0;
}
