#include "basis_params.hpp"
#include "hamiltonian.hpp"
#include "derivatives.hpp"
#include <iostream>
#include <iomanip>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>

using namespace ecg1d;

// Read basis function parameters from a CSV file generated by the Python script.
// Format: one line per complex number, "real,imag"
// File structure: for each basis function: u(1), A(N*N), B(N*N), R(N), name(1)
static std::vector<BasisParams> load_basis_from_csv(const std::string& filename, int N, int basis_n) {
    std::ifstream fin(filename);
    if (!fin.is_open()) {
        std::cerr << "Cannot open " << filename << std::endl;
        return {};
    }

    auto read_complex = [&]() -> Cd {
        std::string line;
        std::getline(fin, line);
        std::stringstream ss(line);
        double re, im;
        char comma;
        ss >> re >> comma >> im;
        return Cd(re, im);
    };

    auto read_int = [&]() -> int {
        std::string line;
        std::getline(fin, line);
        return std::stoi(line);
    };

    std::vector<BasisParams> basis(basis_n);
    for (int k = 0; k < basis_n; k++) {
        basis[k].u = read_complex();
        basis[k].A = MatrixXcd(N, N);
        for (int i = 0; i < N; i++)
            for (int j = 0; j < N; j++)
                basis[k].A(i, j) = read_complex();
        basis[k].B = MatrixXcd(N, N);
        for (int i = 0; i < N; i++)
            for (int j = 0; j < N; j++)
                basis[k].B(i, j) = read_complex();
        basis[k].R = VectorXcd(N);
        for (int i = 0; i < N; i++)
            basis[k].R(i) = read_complex();
        basis[k].name = read_int();
    }
    return basis;
}

static void print_complex(const std::string& label, Cd v) {
    std::cout << label << ": " << v.real() << " + " << v.imag() << "i" << std::endl;
}

static void run_phase1(const std::vector<BasisParams>& basis, int N) {
    std::cout << "=== Phase 1: Functionals ===" << std::endl;

    Cd S = overlap(basis);
    print_complex("Overlap", S);

    Cd T = kinetic_energy_functional(basis);
    print_complex("Kinetic", T);

    Cd V = Harmonic_functional(basis);
    print_complex("Harmonic", V);

    if (N >= 2) {
        Cd D = Delta_contact_functional(basis);
        print_complex("Delta", D);

        Cd G = Gaussian_interaction_functional(basis);
        print_complex("Gaussian", G);
    }

    Cd K_val = kicking_term_functional(basis);
    print_complex("Kicking", K_val);

    Cd E = (T + V) / S;
    print_complex("E(T+V)/S", E);
}

static void run_phase2(const std::vector<BasisParams>& basis, int N) {
    std::cout << "\n=== Phase 2: Derivatives ===" << std::endl;

    int name0 = basis[0].name;
    int name1 = basis[1].name;

    // partial_z_first tests
    Cd v;

    v = partial_z_first(1, true, basis, name0, 0, 0);
    print_complex("pz_first(1,T," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_first(1, false, basis, name0, 0, 0);
    print_complex("pz_first(1,F," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_first(2, true, basis, name0, 0, 0);
    print_complex("pz_first(2,T," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_first(2, false, basis, name0, 0, 0);
    print_complex("pz_first(2,F," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_first(3, true, basis, name0, 0, 0);
    print_complex("pz_first(3,T," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_first(3, false, basis, name1, 0, 0);
    print_complex("pz_first(3,F," + std::to_string(name1) + ",0,0)", v);

    v = partial_z_first(4, true, basis, name0, 0, 0);
    print_complex("pz_first(4,T," + std::to_string(name0) + ",0,0)", v);

    if (N >= 2) {
        v = partial_z_first(4, true, basis, name0, 0, 1);
        print_complex("pz_first(4,T," + std::to_string(name0) + ",0,1)", v);
    }

    // partial_z_second tests
    v = partial_z_second(2, 2, basis, name0, 0, 0, name0, 0, 0);
    print_complex("pz_second(2,2," + std::to_string(name0) + ",0,0," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_second(1, 1, basis, name0, 0, 0, name0, 0, 0);
    print_complex("pz_second(1,1," + std::to_string(name0) + ",0,0," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_second(1, 2, basis, name0, 0, 0, name0, 0, 0);
    print_complex("pz_second(1,2," + std::to_string(name0) + ",0,0," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_second(3, 2, basis, name0, 0, 0, name0, 0, 0);
    print_complex("pz_second(3,2," + std::to_string(name0) + ",0,0," + std::to_string(name0) + ",0,0)", v);

    v = partial_z_second(4, 2, basis, name0, 0, 0, name0, 0, 0);
    print_complex("pz_second(4,2," + std::to_string(name0) + ",0,0," + std::to_string(name0) + ",0,0)", v);

    if (N >= 2) {
        v = partial_z_second(4, 2, basis, name0, 0, 1, name0, 0, 0);
        print_complex("pz_second(4,2," + std::to_string(name0) + ",0,1," + std::to_string(name0) + ",0,0)", v);
    }

    // calculate_C tests
    v = calculate_C(1, name0, 0, 0, 1, name0, 0, 0, basis);
    print_complex("C(1," + std::to_string(name0) + ",0,0,1," + std::to_string(name0) + ",0,0)", v);

    v = calculate_C(2, name0, 0, 0, 2, name0, 0, 0, basis);
    print_complex("C(2," + std::to_string(name0) + ",0,0,2," + std::to_string(name0) + ",0,0)", v);

    v = calculate_C(3, name0, 0, 0, 2, name0, 0, 0, basis);
    print_complex("C(3," + std::to_string(name0) + ",0,0,2," + std::to_string(name0) + ",0,0)", v);

    v = calculate_C(4, name0, 0, 0, 2, name0, 0, 0, basis);
    print_complex("C(4," + std::to_string(name0) + ",0,0,2," + std::to_string(name0) + ",0,0)", v);
}

int main(int argc, char* argv[]) {
    std::cout << std::setprecision(18);

    std::vector<BasisParams> basis;
    int N = 2, basis_n = 2;

    if (argc >= 5 && std::string(argv[1]) == "--csv") {
        std::string filename = argv[2];
        N = std::stoi(argv[3]);
        basis_n = std::stoi(argv[4]);
        basis = load_basis_from_csv(filename, N, basis_n);
        if (basis.empty()) return 1;
    } else {
        for (int t = 0; t < basis_n; t++) {
            basis.push_back(BasisParams::randoman(N, t, t));
        }
    }

    std::cout << "N=" << N << ", K=" << basis_n << std::endl;

    run_phase1(basis, N);

    if (basis_n >= 2) {
        run_phase2(basis, N);
    }

    return 0;
}
